language: ruby
rvm:
- 3.1.2

script: bundle install && bundle exec jekyll build

exclude: [vendor]

os: windows

deploy:
  provider: pages
  edge: true
  skip_cleanup: true
  keep_history: true
  local-dir: C:\Users\joony\Makeitshort.github.io\first_blog.maker\exampleoutname
  target-branch: master
  github_token: $GITHUB_TOKEN
  on:
    branch: main

branches:
  only:
  - main