language: ruby
rvm:
- 3.1.2

script: bundle install && bundle exec jekyll build

exclude: [vendor]

deploy:
  provider: pages
  edge: true
  skip_cleanup: true
  keep_history: true
  local-dir: C:\Users\joony\Makeitshort.github.io\first_blog.maker\exampleoutname
  target-branch: master
  api_key:
      secure: "SjnST7FH0ZTFEdF4apydoZYuGzx53jXiqXREIRRnmLY92oPr3rZUm+/V9HMo3puq6sBDEoFS7tS1fPZmzUz9pE3yuAeIFodaO1Y2V3K88AoG86Q+7k7qnylv970v8bNZ8e5I7egjp4MDNQeE62tvb/POkwnoorBht1ybp0PXJ8LL8/yMJ+0NM52ggq1nQRQWYJPCdghBsYQuVcuggS+FP1E9UuP+UScfXKDMURy/pUJ3lfLR5Z7DoZ+eO6oLubrfbXesHwqjBnscKqJuLTRLpjZ6r9UeOPt4ipHwRbvhfcioWo3CuV7lgroEiKY1ziNNlkEdWqYxAy97Bj/8DLKwOjPgyfSjsXZVt5DLQY1nohcheMFcvELJsLTut6RXSig/5nE4QM0+47jkTSnoeDbfRBCoRSGDCQwnKs2bTTYhI2r90YxDs0hdV/bKjq6z9eDAXJO58Z29AXXkXOQh+Ooy8rBaHzIz+OpwEirzH/VSx3O9sJtMZXQZWDn+BbnWJZf0tkblux5VXD5iz7NNN6aDn6V4DAKTOl2W2wqG572ds7o7ad9An+d5P3IMib5/LU/+3LRcizXqUom2oSw9Y5SjhQig/jThZFClWwnF5wFCugHb7PTGK7L0mcU7oRI90HLHRRHgw9BxzZ3blczeCWl5mAbLfaJzefTkyK2w2yYrbGY="
  on:
    branch: main

branches:
  only:
  - main