language: ruby
rvm:
- 3.1.2

script: bundle install && bundle exec jekyll build

exclude: [vendor]

deploy:
  provider: pages
  skip_cleanup: true
  github_token: GITHUB_TOKEN
  keep_history: true
  local-dir: C:\Users\joony\Makeitshort.github.io\first_blog.maker\exampleoutname
  target-branch: master
  on:
    branch: main

branches:
  only:
  - main